version: "2"
services:

#ARANGO Agencies Start

    #Arango Agency 1 start
    arangodb-agency1:
      image: arangodb/arangodb
      environment:
        - ARANGO_RANDOM_ROOT_PASSWORD=1
      command: >
        --server.endpoint tcp://0.0.0.0:8530
        --server.jwt-secret secret
        --server.authentication true
        --server.authentication-system-only false
        --server.statistics false
        --foxx.queues false
        --agency.size 5
        --agency.supervision true
        --agency.activate true
        --agency.my-address tcp://arangodb-agency1:8530
        --log.level info
        --agency.endpoint tcp://arangodb-agency1:8530
        --agency.endpoint tcp://arangodb-agency2:8530
        --agency.endpoint tcp://arangodb-agency3:8530
        --agency.endpoint tcp://arangodb-agency4:8530
        --agency.endpoint tcp://arangodb-agency5:8530
    #Arango Agency 1 Finish
     
    #Arango Agency 2 starts 
    arangodb-agency2:
      image: arangodb/arangodb
      environment:
        - ARANGO_RANDOM_ROOT_PASSWORD=1
      command: >
        --server.endpoint tcp://0.0.0.0:8530
        --server.jwt-secret secret
        --server.authentication true
        --server.authentication-system-only false
        --server.statistics false
        --foxx.queues false
        --agency.size 5
        --agency.supervision true
        --agency.activate true
        --agency.my-address tcp://arangodb-agency2:8530
        --log.level info
        --agency.endpoint tcp://arangodb-agency1:8530
        --agency.endpoint tcp://arangodb-agency2:8530
        --agency.endpoint tcp://arangodb-agency3:8530
        --agency.endpoint tcp://arangodb-agency4:8530
        --agency.endpoint tcp://arangodb-agency5:8530
    #Arango Agency 2 Finish
    
    #Arango Agency 3 start
    arangodb-agency3:
      image: arangodb/arangodb
      environment:
        - ARANGO_RANDOM_ROOT_PASSWORD=1
      command: >
        --server.endpoint tcp://0.0.0.0:8530
        --server.jwt-secret secret
        --server.authentication true
        --server.authentication-system-only false
        --server.statistics false
        --foxx.queues false
        --agency.size 5
        --agency.supervision true
        --agency.activate true
        --agency.my-address tcp://arangodb-agency3:8530
        --log.level info
        --agency.endpoint tcp://arangodb-agency1:8530
        --agency.endpoint tcp://arangodb-agency2:8530
        --agency.endpoint tcp://arangodb-agency3:8530
        --agency.endpoint tcp://arangodb-agency4:8530
        --agency.endpoint tcp://arangodb-agency5:8530
    #Arango Agency 3 Finish
    
    #Arango Agency 4 start
    arangodb-agency4:
      image: arangodb/arangodb
      environment:
        - ARANGO_RANDOM_ROOT_PASSWORD=1
      command: >
        --server.jwt-secret secret
        --server.authentication true
        --server.authentication-system-only false
        --server.statistics false
        --server.endpoint tcp://0.0.0.0:8530
        --foxx.queues false
        --agency.size 5
        --agency.supervision true
        --agency.activate true
        --agency.my-address tcp://arangodb-agency4:8530
        --log.level info
        --agency.endpoint tcp://arangodb-agency1:8530
        --agency.endpoint tcp://arangodb-agency2:8530
        --agency.endpoint tcp://arangodb-agency3:8530
        --agency.endpoint tcp://arangodb-agency4:8530
        --agency.endpoint tcp://arangodb-agency5:8530
    #Arango Agency 4 start
    
    #Arango Agency 5 start
    arangodb-agency5:
      image: arangodb/arangodb
      environment:
        - ARANGO_RANDOM_ROOT_PASSWORD=1
      command: >
        --server.jwt-secret secret
        --server.authentication true
        --server.authentication-system-only false
        --server.statistics false
        --foxx.queues false
        --agency.size 5
        --agency.supervision true
        --agency.activate true
        --agency.my-address tcp://arangodb-agency5:8530
        --server.endpoint tcp://0.0.0.0:8530
        --log.level info
        --agency.endpoint tcp://arangodb-agency1:8530
        --agency.endpoint tcp://arangodb-agency2:8530
        --agency.endpoint tcp://arangodb-agency3:8530
        --agency.endpoint tcp://arangodb-agency4:8530
        --agency.endpoint tcp://arangodb-agency5:8530
    #Arango Agency 5 Finish
    
#Arango Agencies Finish


#Arango Coordinates Starts
    
    #Arango cordinate 1 Start
    arangodb-coordinator1:
      image: arangodb/arangodb
      environment:
        - ARANGO_RANDOM_ROOT_PASSWORD=1
      command: >
        --server.endpoint tcp://0.0.0.0:8529
        --server.authentication true
        --server.authentication-system-only false
        --server.jwt-secret secret
        --server.statistics true
        --foxx.queues true
        --cluster.agency-endpoint tcp://arangodb-agency1:8530
        --cluster.agency-endpoint tcp://arangodb-agency2:8530
        --cluster.agency-endpoint tcp://arangodb-agency3:8530
        --cluster.agency-endpoint tcp://arangodb-agency4:8530
        --cluster.agency-endpoint tcp://arangodb-agency5:8530
        --cluster.my-address tcp://arangodb-coordinator1:8529
        --cluster.my-local-info COORD1
        --cluster.my-role COORDINATOR
        --log.level info     
      ports: ['8000:8529']
    #Arango cordinate 1 Finish
    
    #Arango coordinate 2 Start
    arangodb-coordinator2:
      image: arangodb/arangodb
      environment:
        - ARANGO_RANDOM_ROOT_PASSWORD=1
      command: >
        --cluster.agency-endpoint tcp://arangodb-agency1:8530
        --cluster.agency-endpoint tcp://arangodb-agency2:8530
        --cluster.agency-endpoint tcp://arangodb-agency3:8530
        --cluster.agency-endpoint tcp://arangodb-agency4:8530
        --cluster.agency-endpoint tcp://arangodb-agency5:8530
        --cluster.my-address tcp://arangodb-coordinator2:8529
        --server.endpoint tcp://0.0.0.0:8529
        --server.jwt-secret secret
        --server.authentication true
        --server.authentication-system-only false
        --server.statistics true
        --foxx.queues true
        --cluster.my-local-info COORD2
        --cluster.my-role COORDINATOR
        --log.level info
    #Arango coordinate 2 Finish
    
    #Arango coordinate 3 Start
    arangodb-coordinator3:
      image: arangodb/arangodb
      environment:
        - ARANGO_RANDOM_ROOT_PASSWORD=1
      command: >
        --server.endpoint tcp://0.0.0.0:8529
        --server.authentication true
        --server.authentication-system-only false
        --server.jwt-secret secret
        --server.statistics true
        --foxx.queues true
        --cluster.agency-endpoint tcp://arangodb-agency1:8530
        --cluster.agency-endpoint tcp://arangodb-agency2:8530
        --cluster.agency-endpoint tcp://arangodb-agency3:8530
        --cluster.agency-endpoint tcp://arangodb-agency4:8530
        --cluster.agency-endpoint tcp://arangodb-agency5:8530
        --cluster.my-address tcp://arangodb-coordinator3:8529
        --cluster.my-local-info COORD3
        --cluster.my-role COORDINATOR
        --log.level info     
      ports: ['8001:8529']
    #Arango coordinate 3 Finish
    
    #Arango coordinate 4 Start
    arangodb-coordinator4:
      image: arangodb/arangodb
      environment:
        - ARANGO_RANDOM_ROOT_PASSWORD=1
      command: >
        --server.endpoint tcp://0.0.0.0:8529
        --server.authentication true
        --server.authentication-system-only false
        --server.jwt-secret secret
        --server.statistics true
        --foxx.queues true
        --cluster.agency-endpoint tcp://arangodb-agency1:8530
        --cluster.agency-endpoint tcp://arangodb-agency2:8530
        --cluster.agency-endpoint tcp://arangodb-agency3:8530
        --cluster.agency-endpoint tcp://arangodb-agency4:8530
        --cluster.agency-endpoint tcp://arangodb-agency5:8530
        --cluster.my-address tcp://arangodb-coordinator4:8529
        --cluster.my-local-info COORD4
        --cluster.my-role COORDINATOR
        --log.level info     
      ports: ['8002:8529'] 
    #Arango coordinate 4 Finish    
#Arango coordinate 4 Finish     

#ARANGO DBSERVERS Start
    
    #ARANGO DBSERVER 1 Start
    arangodb-dbserver1:
      image: arangodb/arangodb
      environment:
        - ARANGO_RANDOM_ROOT_PASSWORD=1
      command: >
        --server.endpoint tcp://0.0.0.0:8529
        --server.authentication true
        --server.authentication-system-only false
        --server.jwt-secret secret
        --server.statistics true
        --foxx.queues false
        --cluster.agency-endpoint tcp://arangodb-agency1:8530
        --cluster.agency-endpoint tcp://arangodb-agency2:8530
        --cluster.agency-endpoint tcp://arangodb-agency3:8530
        --cluster.agency-endpoint tcp://arangodb-agency4:8530
        --cluster.agency-endpoint tcp://arangodb-agency5:8530
        --cluster.my-address tcp://arangodb-dbserver1:8529
        --cluster.my-local-info DB1
        --cluster.my-role PRIMARY
        --log.level info
    #ARANGO DBSERVER 1 Finish
    
    #ARANGO DBSERVER 2 Start
    arangodb-dbserver2:
      image: arangodb/arangodb
      environment:
        - ARANGO_RANDOM_ROOT_PASSWORD=1
      command: >
        --cluster.agency-endpoint tcp://arangodb-agency1:8530
        --cluster.agency-endpoint tcp://arangodb-agency2:8530
        --cluster.agency-endpoint tcp://arangodb-agency3:8530
        --cluster.agency-endpoint tcp://arangodb-agency4:8530
        --cluster.agency-endpoint tcp://arangodb-agency5:8530
        --cluster.my-address tcp://arangodb-dbserver2:8529
        --server.endpoint tcp://0.0.0.0:8529
        --server.jwt-secret secret
        --server.authentication true
        --server.authentication-system-only false
        --server.statistics true
        --foxx.queues false
        --cluster.my-local-info HAVDB1
        --cluster.my-role PRIMARY
        --log.level info
    #ARANGO DBSERVER 2 Finish
    
    #ARANGO DBSERVER 3 Start
    arangodb-dbserver3:
      image: arangodb/arangodb
      environment:
        - ARANGO_RANDOM_ROOT_PASSWORD=1
      command: >
        --cluster.agency-endpoint tcp://arangodb-agency1:8530
        --cluster.agency-endpoint tcp://arangodb-agency2:8530
        --cluster.agency-endpoint tcp://arangodb-agency3:8530
        --cluster.agency-endpoint tcp://arangodb-agency4:8530
        --cluster.agency-endpoint tcp://arangodb-agency5:8530
        --cluster.my-address tcp://arangodb-dbserver3:8529
        --server.endpoint tcp://0.0.0.0:8529
        --server.jwt-secret secret
        --server.authentication true
        --server.authentication-system-only false
        --server.statistics true
        --foxx.queues false
        --cluster.my-local-info HAVDB2
        --cluster.my-role PRIMARY
        --log.level info
    #ARANGO DBSERVER 3 Finish
    
    #ARANGO DBSERVER 4 Start    
    arangodb-dbserver4:
      image: arangodb/arangodb
      environment:
        - ARANGO_RANDOM_ROOT_PASSWORD=1
      command: >
        --cluster.agency-endpoint tcp://arangodb-agency1:8530
        --cluster.agency-endpoint tcp://arangodb-agency2:8530
        --cluster.agency-endpoint tcp://arangodb-agency3:8530
        --cluster.agency-endpoint tcp://arangodb-agency4:8530
        --cluster.agency-endpoint tcp://arangodb-agency5:8530
        --cluster.my-address tcp://arangodb-dbserver4:8529
        --server.endpoint tcp://0.0.0.0:8529
        --server.jwt-secret secret
        --server.authentication true
        --server.authentication-system-only false
        --server.statistics true
        --foxx.queues false
        --cluster.my-local-info HAVDB3
        --cluster.my-role PRIMARY
        --log.level info
    #ARANGO DBSERVER 4 Finish
    
#ARANGO DBSERVERs Finish